### ISSUE TITLE
Loading a parameter values via file

### ISSUE THREAD

**Issue by shaun-edwards** [cbandera/rosparam_handler#10]
ROS parameters can be loaded [directly using param](http://wiki.ros.org/roslaunch/XML/param) or via [yaml using rosparam](http://wiki.ros.org/roslaunch/XML/rosparam) in a launch file.  Dynamic reconfigure can be similarly initialized using the dump/load methods documented [here](http://wiki.ros.org/dynamic_reconfigure#dynamic_reconfigure.2BAC8-groovy.dynparam_dump), although this method does not guarantee a successful init.

Such functionality is useful when the parameter values for a deployed node have been pre-determined, but are not the same for every node of that type.  For example a "perception node" may have several parameters that are tuned for a specific application.

Is there a way to load paramaters from a file using `rosparam_handler`?

BTW...thanks for creating this packages.  It addresses a lot of my issues with ROS parameters and dynamic reconfigure.

**Comment by cbandera** [comment]
Hi,
have a look at the [tutorial](https://github.com/cbandera/rosparam_handler_tutorial) and espacially at the launch files. There I include a yaml file to overwrite some parameters upon launch. 

Hope this helps, cbandera
