### ISSUE TITLE
[bug] generate_dynamic_reconfigure_options called with empty arguments...

### ISSUE THREAD

**Issue by wsascha** [cbandera/rosparam_handler#13]
...when rosparam handler is used without having any .params files in the cfg directory
See: https://github.com/cbandera/rosparam_handler/blob/master/cmake/rosparam_handler-macros.cmake#L67

We fixed this with:
```
list(APPEND ${PROJECT_NAME}_LOCAL_CFG_FILES "${_cfg}")
```

**Comment by cbandera** [comment]
Thanks for the hint!
