### ISSUE TITLE
Check for existing compiler flags

### ISSUE THREAD

**Issue by m-naumann** [cbandera/rosparam_handler#16]
Related to commit 94d61e369fbc18a5739da5a4680d9cdbb681a5a0

Could you check whether a compiler flag >=11 is already set and only set it if required? Otherwize, superior version become degraded (e.g. c++14, as set by the [mrt_cmake_modules](https://github.com/KIT-MRT/mrt_cmake_modules/blob/master/cmake/Modules/UseMrtStdCompilerFlags.cmake#L16))? Thanks

**Comment by cbandera** [comment]
Hi @m-naumann thanks for pointing out.
Could you please test commit c50fb5c in your environment and see whether it fixes the problem?

**Comment by m-naumann** [comment]
Hi @cbandera ,
thanks, commit c50fb5c works with the mrt_cmake_modules! I'd appreciate its merge into master.
