### ISSUE TITLE
Releasing rosparam_handler

### ISSUE THREAD

**Issue by artivis** [cbandera/rosparam_handler#17]
Hi,

it would be great if `rosparam_handler` would be released.  
Is it something you could do ? I can provide some help if you need.

Cheers.

**Comment by cbandera** [comment]
Do you mean released in terms of a rospack package? Could you point me to some documentation of how to release a new package?

**Comment by artivis** [comment]
Yes sure, please check this neat tuto : [FirstTimeRelease](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease)

**Comment by artivis** [comment]
#18 seems necessary for releasing.

**Comment by cbandera** [comment]
Hi @artivis, which distro are you using? Or which distros would you recommend making releases for?

**Comment by artivis** [comment]
I'm currently using both Indigo and Kinetic.  
You can use the same branch for releasing under different ros distro, assuming there are no changes to do for the code to work across those distros.

**Comment by cbandera** [comment]
So, I think the [jade](https://github.com/ros/rosdistro/pull/15123) release is through and ready to use.
Today I have released the package for [indigo](https://github.com/ros/rosdistro/pull/15224) & [kinetic](https://github.com/ros/rosdistro/pull/15223), but it will take a while until its merged and available. Please let me know, whether it's working out for you.

**Comment by artivis** [comment]
Thanks a lot for your efforts, I will give it a shot asap.

**Comment by procopiostein** [comment]
the releases for the three distros are already available at shadowfixed. we have to wait for them to be manually moved to the main repos, but I believe the release process is complete and the issue can be closed IMO.

**Comment by cbandera** [comment]
I still need to update the README once the package is available at the main repo. I'll leave the issue open as a reminder for myself.

**Comment by artivis** [comment]
I have a Travis job that relies on `rosparam_handler` (Indigo version) and everything compiles fine :+1: .
