### ISSUE TITLE
 [Feature Request] Manually upload parameter object content to parameter server

### ISSUE THREAD

**Issue by GDwag** [cbandera/rosparam_handler#31]
This is kind of a follow-up idea to the already implemented "Set default values on parameter server if no value is set" request,

I would like to manually upload the current parameters of the parameter object to the server at any time.
This is meant to enable me to save multiple "sessions" of my project in multiple parameter instances at a time. (like having a list of parameter objects and "re-loading" one of them as the one being currently worked on)

Thanks in advance! :)

**Comment by cbandera** [comment]
Hi, thanks for the idea. 
Would a simple params.setOnServer() be enough for your use case?

**Comment by GDwag** [comment]
Yes it would! Thanks for dealing with my issue!
