### ISSUE TITLE
Develop branch compilation fails when CATKIN_ENABLE_TESTING true

### ISSUE THREAD

**Issue by artivis** [cbandera/rosparam_handler#34]
Compilation fails with the following error message printed 6 times

```terminal
************************************************************************************************
Error when setting up parameter 'ParameterGenerator: Unexpected amount of args, did you try to call this directly? You shouldn't do this!':

************************************************
```

**Comment by artivis** [comment]
Looks like a dependency issue, calling build 2-3 times helps the compilation going through.

**Comment by artivis** [comment]
If `rosparam_handler` is installed (from apt-get), the `.params` files generated for testing uses the installed version rather than the one currently building.

**Comment by zwkcoding** [comment]
I met the same problem when building from the branch `feature/parameters_base`

**Comment by artivis** [comment]
The branch `feature/parameters_base` is based on branch `develop` and does not fix this issue.  
Unfortunately I can't reproduce it on my desktop. I'll try later on ...

**Comment by artivis** [comment]
@zwkcoding This issue should be fixed now on both `develop` and `feature/parameters_base` branch.  
Could you please confirm it ??  
Please notice that I forced pushed branch `feature/parameters_base`, thus you may have to delete your local branch to fetch it again from upstream.

**Comment by zwkcoding** [comment]
Sorry for late reply. It compiles with no error after the fix. Thanks @artivis
