### ISSUE TITLE
Error: "Parameter 'foo/bar' is not defined."

### ISSUE THREAD

**Issue by beetleskin** [cbandera/rosparam_handler#47]
With the release of version 0.1.2. this week, I get errors for all parameters listed in a .params file when launching my stack.

Location:
`src/rosparam_handler/include/rosparam_handler/utilities.hpp:getParam:136`

**Comment by artivis** [comment]
Hi, please could you provide a little more information as what is your error ? Could it be a namespace issue ?

**Comment by beetleskin** [comment]
Error: "Parameter 'foo/bar' is not defined." Whereas "foo" is my node and "bar" is my parameter I define according to your specs within the .params file.

I don't think this is a namespace issue. I didn't change anything despite switching to the shortly released new rosparam_handler version.
