### ISSUE TITLE
Integration with actionlib causes compiling error

### ISSUE THREAD

**Issue by dambrosio** [cbandera/rosparam_handler#57]
Hello,
I ran across a fairly weird issue when I was integrating an action with a rosparam_handler. It seems as if an auto-generated action header is included before the auto-generated parameter header a compilation error is thrown. If the parameter header is after the action header it compiles fine.

I replicated the error using the rosparam_handler_tutorial package on a [forked branch](https://github.com/dambrosio/rosparam_handler_tutorial/tree/bug/action-header.DPA). See [header include](https://github.com/dambrosio/rosparam_handler_tutorial/blob/bug/action-header.DPA/src/demo/demo.hpp#L9) source code.

**Comment by artivis** [comment]
Hi @dambrosio, thanks for reporting this issue !
Pull request #58 seems to fix it. 
Do you mind giving it a shot to double check ??

**Comment by dambrosio** [comment]
@artivis compiles on my side. Thanks for the fix.
