### ISSUE TITLE
Releasing a melodic package?

### ISSUE THREAD

**Issue by destogl** [cbandera/rosparam_handler#67]
Hi @cbandera,
is there possibility to release melodic package of this repository?

Thanks!

**Comment by cbandera** [comment]
Hi Denis, thank you for your interest in this project. 
 I don't maintain this package personally anymore as I am no longer working with ROS on a regular basis. 
However, @artivis was so kind as to take over maintenance.

**Comment by artivis** [comment]
Hi @destogl, 
this package was released for [melodic about a year ago](https://github.com/cbandera/rosparam_handler-release#rosparam_handler-melodic---014-1), it is indeed indexed in [melodic rosdistro](https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml#L8521). I checked this morning and `apt` finds it on my host. Can you please double check and let me know if you have any issue installing it?

**Comment by destogl** [comment]
Hi @artivis,

thanks! Sorry for the disturbance! I didn't look well....
